### ISSUE TITLE
sdk version error

### ISSUE THREAD

**Issue by PawnGeek** [milvus-io/milvus-sdk-go#24]
https://github.com/milvus-io/milvus-sdk-go/blob/d04c04fcbd1c3adf417681d4bae77c63fd233197/milvus/MilvusClient.go#L25

Is there 0.3.0 version ？

**Comment by fishpenguin** [comment]
> https://github.com/milvus-io/milvus-sdk-go/blob/d04c04fcbd1c3adf417681d4bae77c63fd233197/milvus/MilvusClient.go#L25
> 
> Is there 0.3.0 version ？

Yes, there should be  0.3.0 version. I will fix it immediately

**Comment by fishpenguin** [comment]
Already fixed
