### ISSUE TITLE
[Bug]: Search with binary vector

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus-sdk-go#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`vector2Placeholder` considers `entity.Vector` as `FloatVector`, and uses ` server.PlaceholderType_FloatVector` as its type in placeholder. 
But it may be a `BinaryVector`.

``` go
func vector2Placeholder(vectors []entity.Vector) *server.PlaceholderValue {
	ph := &server.PlaceholderValue{
		Tag:    "$0",
		Type:   server.PlaceholderType_FloatVector,
		Values: make([][]byte, 0, len(vectors)),
	}
	for _, vector := range vectors {
		ph.Values = append(ph.Values, vector.Serialize())
	}
	return ph
}

```

**Comment by congqixia** [comment]
Nice catch. Will fix this bug soon.
