### ISSUE TITLE
[Enhancement]: LoadCollectionOption needs to add `WithResourceGroups` 

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus-sdk-go#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

go-version: v2.2.1

LoadCollectionOption needs to add `WithResourceGroups` to support load multi replicas into multi resource groups

![image](https://user-images.githubusercontent.com/27288593/227204694-6c861456-d548-4f40-a40f-24474994d27b.png)

**Comment by ThreadDao** [comment]
@congqixia

**Comment by congqixia** [comment]
Mark as done
/close
