### ISSUE TITLE
[Bug]: Insert rows data of FieldTypeFloat16Vector and FieldTypeBFloat16Vector gets error: expected unhandled field

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus-sdk-go#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. create collection with fields: FieldTypeFloat16Vector and FieldTypeBFloat16Vector
2. insert row data
```
2024/03/15 16:10:15 milvus_client.go:14: (ApiRequest): func [InsertRows], args: [context.Background.WithDeadline(2024-03-15 16:12:15.607890821 +0800 CST m=+120.003386323 [1m59.725333128s]) bEfo  3000]
2024/03/15 16:10:15 milvus_client.go:19: (ApiResponse): func [InsertRows], error: expected unhandled field fp16Vec
```
3. reason: func AnyToColumns in entity package row.go file not handle the new dataType
![image](https://github.com/milvus-io/milvus-sdk-go/assets/27288593/4687d127-51ab-4cd3-865c-f373f633c2ec)

**Comment by congqixia** [comment]
/assign @ThreadDao 
Patch merged, could you please verify?

**Comment by ThreadDao** [comment]
fixed
