### ISSUE TITLE
[Bug]: How to iterate through custom field

### ISSUE THREAD

**Issue by Erodotos** [milvus-io/milvus-sdk-go#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

How to get the values of a field and iterate through it? 

I have this code which is wrong and not working.

```
animals, _ := result[0].Fields.GetColumn("animals")
```

Went trough the documentation but did not find anything.  Any kind of guidance would be appreciated.

**Comment by RomitSingh1999** [comment]
@Erodotos What is the error you are getting?

**Comment by Erodotos** [comment]
> @Erodotos What is the error you are getting?

I dont get an error. 

I am just trying to extract the column values in an array or slice but I can not find if there is a way to do this. 

The returned struct is of `entity.Column type`, which is an interface.

**Comment by Erodotos** [comment]
Issue resolved. Found how to iterate result after looking at the example [here](https://github.com/milvus-io/milvus-sdk-go/blob/master/examples/insert/insert.go
)

Answer on lines 120 - 141
