### ISSUE TITLE
[QUESTION] Milvus version

### ISSUE THREAD

**Issue by Noomegipy** [milvus-io/milvus-sdk-go#88]
Hello!
Could you tell me please what happened with 11.0 milvus? Its weird by it looks like deprecated, but 10.5 looks like actual. Which version should i take? I also ask because golang sdk 0.45 using float32 in Entity struct ->
it probably means less accurate search and i need float64 -  but it is only in the sdk version 5.0.0 for milvus version 11.0.
Please help:)

Sorry if this is a frequent question

**Comment by fishpenguin** [comment]
milvus-0.11.0 has been removed
We always use float32 for float vector, in go-sdk-0.4.5, the float64 is used for structured index but not vector.

**Comment by fishpenguin** [comment]
Closed.
